name: Release extension
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: hydrogen
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install VSCE
        run: npm install -g @vscode/vsce
      - name: Package extension
        run: vsce package
      - name: Get release version
        id: get-version
        run: echo "version=tailwind-theme-$(sed -E 's/^refs\/tags\/v//' <<< ${{ github.ref }}).vsix" >> "$GITHUB_OUTPUT"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.get-version.outputs.version }}